AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer + Security Groups

Resources:

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !ImportValue services-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Security Group
      VpcId: !ImportValue services-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: feedback-alb
      Scheme: internet-facing
      Type: application
      Subnets:
        - !ImportValue services-public-subnet-1
        - !ImportValue services-public-subnet-2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: feedback-tg
      Port: 5000
      Protocol: HTTP
      TargetType: ip
      VpcId: !ImportValue services-vpc-id
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: alb-target-group

  ECSSecurityGroupId:
    Value: !Ref ECSSecurityGroup
    Export:
      Name: ecs-sg

  ALBDNS:
    Value: !GetAtt ALB.DNSName
